In [1]:
# Using method with cofactors

In [4]:
import numpy as np

In [115]:
def get_minor(A, i, j):
    useful_elements = np.array([])
    for i_ in range(len(A)):
        if i == i_:
            continue
        for j_ in range(len(A[0])):
            if j == j_:
                continue
            
            useful_elements = np.append(useful_elements, A[i_][j_])
            
    return np.linalg.det(useful_elements.reshape((A.shape[0]-1, A.shape[1]-1)))

def get_cofactors(A):
    cofactors = np.empty_like(A, dtype=float)
    for i in range(len(A)):
        for j in range(len(A[0])):
            cofactors[i][j] = ((-1)**(i+j+2))*get_minor(A, i, j)
    return cofactors

def get_inverse(A):
    detA = np.linalg.det(A)
    if detA == 0:
        return None
    return (1/detA) * get_cofactors(A).T

In [117]:
print(get_inverse(A))
print(np.matmul(A, get_inverse(A)))

[[-0.5         1.         -0.5       ]
 [-0.5        -2.          1.5       ]
 [ 0.83333333  1.         -0.83333333]]
[[1.0000000e+00 0.0000000e+00 4.4408921e-16]
 [8.8817842e-16 1.0000000e+00 8.8817842e-16]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00]]
