In [1]:
import numpy as np
from math import ceil
from sys import path
path.append("/Users/reid/dev/PythonCode/tm/tools")
from tools import *

In [17]:
# Define network architecture and inputs and outputs
R = 6
inputs, outputs, S = gen_inputs_outputs(R)

In [9]:
# Convert the inputs and outputs to ones and negative ones
inputs = hardsym(inputs)
outputs = hardsym(outputs)

In [10]:
inputs

array([[-1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1,  1],
       [-1, -1, -1, -1,  1, -1],
       [-1, -1, -1, -1,  1,  1],
       [-1, -1, -1,  1, -1, -1],
       [-1, -1, -1,  1, -1,  1],
       [-1, -1, -1,  1,  1, -1],
       [-1, -1, -1,  1,  1,  1],
       [-1, -1,  1, -1, -1, -1],
       [-1, -1,  1, -1, -1,  1],
       [-1, -1,  1, -1,  1, -1],
       [-1, -1,  1, -1,  1,  1],
       [-1, -1,  1,  1, -1, -1],
       [-1, -1,  1,  1, -1,  1],
       [-1, -1,  1,  1,  1, -1],
       [-1, -1,  1,  1,  1,  1],
       [-1,  1, -1, -1, -1, -1],
       [-1,  1, -1, -1, -1,  1],
       [-1,  1, -1, -1,  1, -1],
       [-1,  1, -1, -1,  1,  1],
       [-1,  1, -1,  1, -1, -1],
       [-1,  1, -1,  1, -1,  1],
       [-1,  1, -1,  1,  1, -1],
       [-1,  1, -1,  1,  1,  1],
       [-1,  1,  1, -1, -1, -1],
       [-1,  1,  1, -1, -1,  1],
       [-1,  1,  1, -1,  1, -1],
       [-1,  1,  1, -1,  1,  1],
       [-1,  1,  1,  1, -1, -1],
       [-1,  1,  1,  1, -1,  1],
       [-1

In [11]:
outputs

array([[-1, -1, -1, -1],
       [-1, -1, -1,  1],
       [-1, -1,  1, -1],
       [-1, -1,  1,  1],
       [-1,  1, -1, -1],
       [-1,  1, -1,  1],
       [-1,  1,  1, -1],
       [-1,  1,  1,  1],
       [-1, -1, -1,  1],
       [-1, -1,  1, -1],
       [-1, -1,  1,  1],
       [-1,  1, -1, -1],
       [-1,  1, -1,  1],
       [-1,  1,  1, -1],
       [-1,  1,  1,  1],
       [ 1, -1, -1, -1],
       [-1, -1,  1, -1],
       [-1, -1,  1,  1],
       [-1,  1, -1, -1],
       [-1,  1, -1,  1],
       [-1,  1,  1, -1],
       [-1,  1,  1,  1],
       [ 1, -1, -1, -1],
       [ 1, -1, -1,  1],
       [-1, -1,  1,  1],
       [-1,  1, -1, -1],
       [-1,  1, -1,  1],
       [-1,  1,  1, -1],
       [-1,  1,  1,  1],
       [ 1, -1, -1, -1],
       [ 1, -1, -1,  1],
       [ 1, -1,  1, -1],
       [-1,  1, -1, -1],
       [-1,  1, -1,  1],
       [-1,  1,  1, -1],
       [-1,  1,  1,  1],
       [ 1, -1, -1, -1],
       [ 1, -1, -1,  1],
       [ 1, -1,  1, -1],
       [ 1, -1,  1,  1],


In [12]:
# Initialize the weights
W = np.zeros(shape=(S, R), dtype=float)

In [13]:
# Train the weights
for i in range(len(inputs)):
    W = W + np.matmul(outputs[i].reshape(S, 1), inputs[i].reshape(1, R))

In [14]:
W

array([[32., 16.,  8., 32., 16.,  8.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [16]:
# Test the weights
for i in range(len(inputs)):
    print(outputs[i].reshape(S, 1) - hardlims(np.matmul(W, inputs[i].reshape(R, 1))))

[[ 0]
 [-2]
 [-2]
 [-2]]
[[ 0]
 [-2]
 [-2]
 [ 0]]
[[ 0]
 [-2]
 [ 0]
 [-2]]
[[ 0]
 [-2]
 [ 0]
 [ 0]]
[[ 0]
 [ 0]
 [-2]
 [-2]]
[[ 0]
 [ 0]
 [-2]
 [ 0]]
[[ 0]
 [ 0]
 [ 0]
 [-2]]
[[-2]
 [ 0]
 [ 0]
 [ 0]]
[[ 0]
 [-2]
 [-2]
 [ 0]]
[[ 0]
 [-2]
 [ 0]
 [-2]]
[[ 0]
 [-2]
 [ 0]
 [ 0]]
[[ 0]
 [ 0]
 [-2]
 [-2]]
[[ 0]
 [ 0]
 [-2]
 [ 0]]
[[ 0]
 [ 0]
 [ 0]
 [-2]]
[[-2]
 [ 0]
 [ 0]
 [ 0]]
[[ 0]
 [-2]
 [-2]
 [-2]]
[[ 0]
 [-2]
 [ 0]
 [-2]]
[[ 0]
 [-2]
 [ 0]
 [ 0]]
[[ 0]
 [ 0]
 [-2]
 [-2]]
[[ 0]
 [ 0]
 [-2]
 [ 0]]
[[ 0]
 [ 0]
 [ 0]
 [-2]]
[[-2]
 [ 0]
 [ 0]
 [ 0]]
[[ 0]
 [-2]
 [-2]
 [-2]]
[[ 0]
 [-2]
 [-2]
 [ 0]]
[[ 0]
 [-2]
 [ 0]
 [ 0]]
[[ 0]
 [ 0]
 [-2]
 [-2]]
[[ 0]
 [ 0]
 [-2]
 [ 0]]
[[ 0]
 [ 0]
 [ 0]
 [-2]]
[[-2]
 [ 0]
 [ 0]
 [ 0]]
[[ 0]
 [-2]
 [-2]
 [-2]]
[[ 0]
 [-2]
 [-2]
 [ 0]]
[[ 0]
 [-2]
 [ 0]
 [-2]]
[[ 0]
 [ 0]
 [-2]
 [-2]]
[[ 0]
 [ 0]
 [-2]
 [ 0]]
[[ 0]
 [ 0]
 [ 0]
 [-2]]
[[-2]
 [ 0]
 [ 0]
 [ 0]]
[[ 0]
 [-2]
 [-2]
 [-2]]
[[ 0]
 [-2]
 [-2]
 [ 0]]
[[ 0]
 [-2]
 [ 0]
 [-2]]
[[ 0]
 [-2]
 [ 0]
 [ 0]]
