In [1]:
import numpy as np
from math import ceil
from sys import path
path.append("../tools")
from tools import *

In [2]:
# Define network architecture and inputs and outputs
R = 4
inputs, outputs, S = gen_inputs_outputs(R)

In [3]:
# Generate symetric inputs and outpts
s_inputs = hardsym(inputs)
s_outputs = hardsym(outputs)

In [4]:
print(inputs, s_inputs)

[[0 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 1 1]
 [0 1 0 0]
 [0 1 0 1]
 [0 1 1 0]
 [0 1 1 1]
 [1 0 0 0]
 [1 0 0 1]
 [1 0 1 0]
 [1 0 1 1]
 [1 1 0 0]
 [1 1 0 1]
 [1 1 1 0]
 [1 1 1 1]] [[-1 -1 -1 -1]
 [-1 -1 -1  1]
 [-1 -1  1 -1]
 [-1 -1  1  1]
 [-1  1 -1 -1]
 [-1  1 -1  1]
 [-1  1  1 -1]
 [-1  1  1  1]
 [ 1 -1 -1 -1]
 [ 1 -1 -1  1]
 [ 1 -1  1 -1]
 [ 1 -1  1  1]
 [ 1  1 -1 -1]
 [ 1  1 -1  1]
 [ 1  1  1 -1]
 [ 1  1  1  1]]


In [5]:
print(outputs, s_outputs)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]] [[-1 -1 -1]
 [-1 -1  1]
 [-1  1 -1]
 [-1  1  1]
 [-1 -1  1]
 [-1  1 -1]
 [-1  1  1]
 [ 1 -1 -1]
 [-1  1 -1]
 [-1  1  1]
 [ 1 -1 -1]
 [ 1 -1  1]
 [-1  1  1]
 [ 1 -1 -1]
 [ 1 -1  1]
 [ 1  1 -1]]


In [6]:
# Initialize the weights 
W = np.zeros(shape=(S, R), dtype=float)

# Initialize the weights for a symetric network
s_W = np.zeros(shape=(S, R), dtype=float)

In [7]:
# Train the weights
for i in range(len(inputs)):
    W = W + np.matmul(outputs[i].reshape(S, 1), inputs[i].reshape(1, R))

# Train the weights for the symetric network
for i in range(len(s_inputs)):
    s_W = s_W + np.matmul(s_outputs[i].reshape(S, 1), s_inputs[i].reshape(1, R))

In [8]:
W

array([[5., 4., 5., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [9]:
s_W

array([[8., 4., 8., 4.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
# Test the weights for hardlim
err = []

for i in range(len(inputs)):
    err.append(outputs[i].reshape(S, 1) - hardlim(np.matmul(W, inputs[i].reshape(R, 1))))

print(e2(err))

[23]


In [11]:
# Test the weights without transfer function
for i in range(len(inputs)):
    print(outputs[i].reshape(S, 1) - np.matmul(s_W, s_inputs[i].reshape(R, 1)))

[[24.]
 [ 0.]
 [ 0.]]
[[16.]
 [ 0.]
 [ 1.]]
[[8.]
 [1.]
 [0.]]
[[0.]
 [1.]
 [1.]]
[[16.]
 [ 0.]
 [ 1.]]
[[8.]
 [1.]
 [0.]]
[[0.]
 [1.]
 [1.]]
[[-7.]
 [ 0.]
 [ 0.]]
[[8.]
 [1.]
 [0.]]
[[0.]
 [1.]
 [1.]]
[[-7.]
 [ 0.]
 [ 0.]]
[[-15.]
 [  0.]
 [  1.]]
[[0.]
 [1.]
 [1.]]
[[-7.]
 [ 0.]
 [ 0.]]
[[-15.]
 [  0.]
 [  1.]]
[[-23.]
 [  1.]
 [  0.]]


In [12]:
# Test the with the hardlim transfert function
for i in range(len(inputs)):
    print(outputs[i].reshape(S, 1) - hardlim(np.matmul(W, inputs[i].reshape(R, 1))))

[[0]
 [0]
 [0]]
[[-1]
 [-1]
 [ 0]]
[[-1]
 [ 0]
 [-1]]
[[-1]
 [ 0]
 [ 0]]
[[-1]
 [-1]
 [ 0]]
[[-1]
 [ 0]
 [-1]]
[[-1]
 [ 0]
 [ 0]]
[[ 0]
 [-1]
 [-1]]
[[-1]
 [ 0]
 [-1]]
[[-1]
 [ 0]
 [ 0]]
[[ 0]
 [-1]
 [-1]]
[[ 0]
 [-1]
 [ 0]]
[[-1]
 [ 0]
 [ 0]]
[[ 0]
 [-1]
 [-1]]
[[ 0]
 [-1]
 [ 0]]
[[ 0]
 [ 0]
 [-1]]
