# This model uses https://hagan.okstate.edu/NNDesign.pdf p.68

In [1]:
import numpy as np

In [2]:
# Define first layer's weights based off of the different prototype arrays
# The different caracteristics are:
# 2 legs | 4 legs | wings | fins | pointy ears | floppy ears | tail | big | hair | scales | claws
# The different animals are:
# Dog
# Cat
# Bird
# Fish
w_1 = np.array([
    [-1, 1, -1, -1, -1, 1, 1, 1, 1, -1, 1],
    [-1, 1, -1, -1, 1, -1, 1, -1, 1, -1, 1],
    [1, -1, 1, -1, -1, -1, 1, -1, -1, -1, 1],
    [-1, -1, -1, 1, -1, -1, -1, -1, -1, 1, -1],
])
w_1

array([[-1,  1, -1, -1, -1,  1,  1,  1,  1, -1,  1],
       [-1,  1, -1, -1,  1, -1,  1, -1,  1, -1,  1],
       [ 1, -1,  1, -1, -1, -1,  1, -1, -1, -1,  1],
       [-1, -1, -1,  1, -1, -1, -1, -1, -1,  1, -1]])

In [3]:
# Define the first layers biases
b_1 = np.array([len(w_1[0]) for i in range(len(w_1))]).reshape(len(w_1), 1)

In [4]:
b_1

array([[11],
       [11],
       [11],
       [11]])

In [5]:
# Define a function to cacluate output of first layer

In [6]:
def calc_first_layer(p):
    return np.matmul(w_1, p) + b_1

In [7]:
# Define the weights for the second layer
w_2 = np.identity(len(w_1))
for i, array in enumerate(w_2):
    w_2[i][array == 0] = -(1/(len(w_1)-1))

In [8]:
w_2

array([[ 1.        , -0.33333333, -0.33333333, -0.33333333],
       [-0.33333333,  1.        , -0.33333333, -0.33333333],
       [-0.33333333, -0.33333333,  1.        , -0.33333333],
       [-0.33333333, -0.33333333, -0.33333333,  1.        ]])

In [9]:
# Define a function to compete on the second layer
def recurrent_layer(a):
    n = np.matmul(w_2, a)
    output = np.ones(shape=(len(w_1), 1))
    for i in range(len(n)):
        output[i][0] = n[i][0] if n[i][0] > 0 else 0
    return output

# Test the network

In [13]:
# Define an input
# Pig
p = np.array([-1, 1, -1, -1, 1, -1, 1, 1, 1, -1, -1]).reshape(11, 1)

In [14]:
# Get the output for the first layer
a_1 = calc_first_layer(p)

In [15]:
a_1

array([[16],
       [18],
       [ 8],
       [ 8]])

In [16]:
# Now compete for which one is best
a_2 = a_1
while True:
    old_a_2 = a_2
    a_2 = recurrent_layer(a_2)
    same = False
    for i in range(len(a_2)):
        if a_2[i] != old_a_2[i]:
            break
        same = True

    if same == True:
        break
        
a_2

array([[0.       ],
       [4.9382716],
       [0.       ],
       [0.       ]])