In [1]:
# Imports
import numpy as np

In [2]:
# Import the tools
from sys import path
path.append('/Users/reid/dev/PythonCode/tm/tools')
path.append('D:/PythonCode/tm/tools')
from tools import gen_inputs_outputs, logsig, lin, deriv_logsig, deriv_lin, e2

In [3]:
# Define the size of the network
# Order by layers (input, layer1, layer2, ...)
# !!! No output layer yet, wait to gen inputs
layer_sizes = [4, 7]

In [4]:
# Gen inputs, outputs and size of the last layer
inputs, outputs, S = gen_inputs_outputs(layer_sizes[0])

In [5]:
# Append the output layer size
layer_sizes = np.array(layer_sizes + [S], dtype=int)

In [6]:
# Network shape
layer_sizes

array([4, 7, 3])

In [7]:
# Inputs
inputs

array([[0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 1, 0, 0],
       [0, 1, 0, 1],
       [0, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 0, 0, 0],
       [1, 0, 0, 1],
       [1, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 0, 0],
       [1, 1, 0, 1],
       [1, 1, 1, 0],
       [1, 1, 1, 1]])

In [8]:
# Outputs
outputs

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0]])

In [9]:
# Intialize the weights and biases randomly
# Also create the list to store the outputs of each layer
# Store the outptut for each layer
# Finally create the list of the sensitivities
weights_list = []
biases_list = []
n_list = []
a_list = []
s_list = []

In [10]:
# Define a function to reset all the parameters
# This is done to test multiple different network types
def reset_params():
    weights_list.clear()
    biases_list.clear()
    n_list.clear()
    a_list.clear()
    s_list.clear()
    for i in range(1, len(layer_sizes)):
        weights_list.append(np.random.rand(layer_sizes[i], layer_sizes[i-1]))
        biases_list.append(np.random.rand(layer_sizes[i], 1))
        n_list.append(np.empty((layer_sizes[i], 1), dtype=float))
        a_list.append(np.empty((layer_sizes[i], 1), dtype=float))
        s_list.append(np.empty((layer_sizes[i], 1), dtype=float))

In [11]:
# Define the transfer functions
transfer_functions = [logsig, lin]

In [12]:
# Define the vectors with the derivatives of the transfer functions
# These need to be converted to dialation matrices
# but this is done after the partial derivatives are calculated
# so that the numerical values can be multiplied by the identity matrix
# makes my life easier
deriv_transfer_functions = [deriv_logsig, deriv_lin]

In [13]:
# Define a function to calculate the output of the network
# while also saving the data
# Assuming that the input is already a Rx1 matrix
def run_network(X):
    # Get the input for the first layer so that
    # no need to use X and can calculate
    # recursively
    n_list[0] = np.matmul(weights_list[0], X) + biases_list[0]
    a_list[0] = transfer_functions[0](n_list[0])

    # Calculate the rest of the outptut
    for i in range(1, len(weights_list)):
        n_list[i] = np.matmul(weights_list[i], a_list[i-1]) + biases_list[i]
        a_list[i] = transfer_functions[i](n_list[i])

In [14]:
# Calculate the senstivites for the last layer
# Write a function to fill the diagonal of the matrix
def fill_F_dot(layer_num):
    a = np.identity(len(n_list[layer_num]), float)
    np.fill_diagonal(a, deriv_transfer_functions[layer_num](n_list[layer_num]).flatten())
    return a

def train_network(learning_rate=.1, epochs=1):
    for i in range(epochs):
        # Iterate through the inputs and outputs
        for i in range(len(inputs)):
            # Run the network
            run_network(inputs[i].reshape(layer_sizes[0], 1))

            # Get the dialation matrix for the last layer
            F_dot = fill_F_dot(-1)

            # Calculate the sensitivites for the last layer
            s_list[-1] = -2 * np.matmul(F_dot, outputs[i].reshape(layer_sizes[-1], 1)-a_list[-1])

            # Update the weights and biases for the last layer
            weights_list[-1] += -learning_rate*np.matmul(s_list[-1], a_list[-2].T)
            biases_list[-1] += -learning_rate*s_list[-1]

            # Iterate through the remaining layers backwards
            for i in range(len(n_list)-2, 0, -1):
                s_list[i] = np.matmul(np.matmul(fill_F_dot(i), weights_list[i+1].T), s_list[i+1])
                weights_list[i] += -learning_rate*np.matmul(s_list[i], a_list[i-1].T)
                biases_list[i] += -learning_rate*s_list[i]

In [15]:
# Function to evaluate the performance
# of the network
def performance():
    results = np.empty((len(inputs), layer_sizes[-1]), dtype=float)
    for i in range(len(inputs)):
        run_network(inputs[i].reshape(layer_sizes[0], 1))
        results[i] = outputs[i] - a_list[-1].flatten()
    return e2(results)

In [16]:
# Print performance
def print_performance_dict(performance_dict):
    for a in sorted(performance_dict.items(), key=lambda x: x[1]):
        print(f'Error: {a[1]}' + a[0])

In [17]:
# Trains netowrk using the parameters for each bit size
def update_performance_dict(layer_sizes_list, performance_dict):
    for layer_sizes in layer_sizes_list:
        # Get the inputs and outputs for the specifiq network size
        inputs, outputs, S = gen_inputs_outputs(layer_sizes[0])
        layer_sizes.append(S)
    
        # Iterate through the different learning rates
        # and epochs
        for rate in learning_rates:
            for epochs in epochs_list:
                # Reset weights and biases
                reset_params()
                # Train the network
                train_network(learning_rate=rate, epochs=epochs)
                # Update the performance dict
                performance_dict.update({f'Layers: {layer_sizes}, Learning rate: {rate}, Epochs: {epochs}': performance()})

In [18]:
### !!! Do not run code underneath until saving to the file
### It trains 24000 different networks
# Performance dictionnaries of the network
performance_dict_2bits = {}
performance_dict_4bits = {}
performance_dict_8bits = {}

In [19]:
# Parameters that won't change despite differnt layer sizes
# Set different learning rates
learning_rates = [1/(16*(2**i)) for i in range(10)]

# Set the diffrent epochs
epochs_list = [i for i in range(1, 21)]

In [20]:
# Multiple different layer sizes
# Start with 1 hidden layer
layer_sizes_list_2bits = [[4, 2*(2**i)]for i in range(10)]
layer_sizes_list_4bits = [[8, 2*(2**i)]for i in range(10)]
layer_sizes_list_8bits = [[16, 2*(2**i)]for i in range(10)]

In [24]:
# Calculate performance for 1 hidden layer
# 2 bits
update_performance_dict(layer_sizes_list_2bits, performance_dict_2bits)
# 4 bits
update_performance_dict(layer_sizes_list_4bits, performance_dict_4bits)
# 8 bits
update_performance_dict(layer_sizes_list_8bits, performance_dict_8bits)

In [25]:
# 2 Hidden layers
# Redefine the transfer functions
transfer_funtions = [logsig, logsig, lin]
deriv_transfer_functions = [deriv_logsig, deriv_logsig, deriv_lin]

# New layer sizes
layer_sizes_list_2bits = [[4, 2*(2**i), 2*(2**j)] for j in range(10) for i in range(10)]
layer_sizes_list_4bits = [[8, 2*(2**i), 2*(2**j)] for j in range(10) for i in range(10)]
layer_sizes_list_8bits = [[16, 2*(2**i), 2*(2**j)] for j in range(10) for i in range(10)]

In [26]:
# Calculate the performance for 2 hidden layers
# 2 bits
update_performance_dict(layer_sizes_list_2bits, performance_dict_2bits)
# 4 bits
update_performance_dict(layer_sizes_list_4bits, performance_dict_4bits)
# 8 bits
update_performance_dict(layer_sizes_list_8bits, performance_dict_8bits)

In [28]:
print('-'*7 + '2bits' + '-'*7)
print_performance_dict(performance_dict_2bits)
print('-'*7 + '4bits' + '-'*7)
print_performance_dict(performance_dict_4bits)
print('-'*7 + '8bits' + '-'*7)
print_performance_dict(performance_dict_8bits)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



In [40]:
# Save the data of the performance dicts
performance_dicts = [performance_dict_2bits, performance_dict_4bits, performance_dict_8bits]
for i in range(len(performance_dicts)):
    with open(f'/Users/reid/dev/PythonCode/tm/BackPropagationBinaryCalcs/data/{2**(i+1)}bit_performance.txt', 'w') as f:
        f.write('parameters,performance\n')
        f.writelines([f'{x}\n' for x in sorted(list(performance_dicts[i].items()), key=lambda x: x[1], reverse=True)])
### You can run code below this

In [13]:
# Test the model with keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD

In [14]:
model = Sequential()
model.add(Dense(layer_sizes[1], input_shape=(layer_sizes[0],), activation='sigmoid'))
model.add(Dense(layer_sizes[2], activation='linear'))

In [15]:
sdg = SGD(.9)
model.compile(loss="categorical_crossentropy", optimizer=sdg,
	metrics=["accuracy"])
model.fit(inputs, outputs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 196ms/step - accuracy: 0.5000 - loss: 7.0425


In [16]:
model.predict(inputs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step


array([[ 0.01186371, -8.282264  , -1.4656483 ],
       [ 0.0887537 , -9.469966  , -1.5549538 ],
       [ 0.15937938, -8.323184  , -1.3819622 ],
       [ 0.22767666, -9.4916    , -1.4718292 ],
       [-0.01628557, -8.611647  , -1.6199257 ],
       [ 0.04203045, -9.72632   , -1.6907108 ],
       [ 0.14307892, -8.662352  , -1.5352875 ],
       [ 0.20412186, -9.765932  , -1.603532  ]], dtype=float32)