In [1]:
# Imports
import numpy as np

In [2]:
# Import the tools
from sys import path
# path.append('/Users/reid/dev/PythonCode/tm/tools')
path.append('D:/PythonCode/tm/tools')
from tools import gen_inputs_outputs, logsig, lin

In [3]:
# Define the size of the network
# Order by layers (input, layer1, layer2, ...)
# !!! No output layer yet, wait to gen inputs
layer_sizes = [4, 7]

In [4]:
# Gen inputs, outputs and size of the last layer
inputs, outputs, S = gen_inputs_outputs(layer_sizes[0])

In [5]:
# Append the output layer size
layer_sizes = np.array(layer_sizes + [S], dtype=int)

In [6]:
# Network shape
layer_sizes

array([4, 7, 3])

In [7]:
# Inputs
inputs

array([[0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 1, 0, 0],
       [0, 1, 0, 1],
       [0, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 0, 0, 0],
       [1, 0, 0, 1],
       [1, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 0, 0],
       [1, 1, 0, 1],
       [1, 1, 1, 0],
       [1, 1, 1, 1]])

In [8]:
# Outputs
outputs

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0]])

In [9]:
# Intialize the weights and biases randomly
# Also create the list to store the outputs of each layer
weights_list = []
biases_list = []
n_list = []

In [10]:
for i in range(1, len(layer_sizes)):
    weights_list.append(np.random.rand(layer_sizes[i], layer_sizes[i-1]))
    biases_list.append(np.random.rand(layer_sizes[i], 1))
    n_list.append(np.empty((layer_sizes[i], 1)))

In [11]:
weights_list

[array([[0.5910633 , 0.26205679, 0.93175877, 0.70260743],
        [0.63678704, 0.01982164, 0.58001799, 0.04679549],
        [0.33611478, 0.01823042, 0.04103187, 0.62202369],
        [0.71902076, 0.13602348, 0.42554906, 0.37180745],
        [0.26730057, 0.04123119, 0.43473333, 0.76629405],
        [0.30873607, 0.72270571, 0.40831446, 0.14634144],
        [0.06915302, 0.69248233, 0.45004402, 0.41499124]]),
 array([[0.86690231, 0.31583103, 0.5972978 , 0.51895474, 0.1458184 ,
         0.42707839, 0.39360144],
        [0.96731849, 0.29346265, 0.05780342, 0.76009809, 0.49023542,
         0.18781583, 0.49143541],
        [0.25968608, 0.79442207, 0.65874954, 0.41643878, 0.56149373,
         0.33041507, 0.50790023]])]

In [12]:
biases_list

[array([[0.37373712],
        [0.31913834],
        [0.73502281],
        [0.85059082],
        [0.83876614],
        [0.57973857],
        [0.93556432]]),
 array([[0.4267769 ],
        [0.38668555],
        [0.27581543]])]

In [13]:
n_list

[array([[0.00000000e+000],
        [0.00000000e+000],
        [0.00000000e+000],
        [0.00000000e+000],
        [0.00000000e+000],
        [0.00000000e+000],
        [2.42396074e-154]]),
 array([[3.11523751e-307],
        [4.45044650e-307],
        [4.45036841e-307]])]

In [14]:
# Define the transfer functions
transfer_functions = [logsig, lin]

In [ ]:
# Define the vectors with the partial derivatives of the transfer functions
# These need to be converted to dialation matrices
# but this is done after the partial derivatives are calculated
# so that the numerical values can be multiplied by the identity matrix
partial_transfer_functions = [partial_logsig, partial_lin]