In [1]:
# Imports
import numpy as np

In [5]:
# Import the tools
from sys import path
path.append('/Users/reid/dev/PythonCode/tm/tools')
from tools import gen_inputs_outputs

In [48]:
# Define the size of the network
# Order by layers (input, layer1, layer2, ...)
# !!! No output layer yet, wait to gen inputs
layer_sizes = [4, 7]

In [49]:
# Gen inputs, outputs and size of the last layer
inputs, outputs, S = gen_inputs_outputs(layer_sizes[0])

In [50]:
# Append the output layer size
layer_sizes = np.array(layer_sizes + [S], dtype=int)

In [51]:
# Network shape
layer_sizes

array([4, 7, 3])

In [52]:
# Inputs
inputs

array([[0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 1, 0, 0],
       [0, 1, 0, 1],
       [0, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 0, 0, 0],
       [1, 0, 0, 1],
       [1, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 0, 0],
       [1, 1, 0, 1],
       [1, 1, 1, 0],
       [1, 1, 1, 1]])

In [53]:
# Outputs
outputs

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0]])

In [64]:
# Intialize the weights randomly
weights_list = []

In [65]:
# Fill the weights randomly
for i in range(1, len(layer_sizes)):
    weights_list.append(np.random.rand(layer_sizes[i], layer_sizes[i-1]))

In [66]:
weights_list

[array([[0.37430306, 0.68550797, 0.45279109, 0.31433416],
        [0.97738381, 0.74959943, 0.74436045, 0.84289531],
        [0.14384737, 0.19797891, 0.26550819, 0.59139698],
        [0.96802599, 0.7326053 , 0.25076569, 0.9135021 ],
        [0.42250027, 0.62245307, 0.85453509, 0.50398294],
        [0.30647059, 0.08864874, 0.82619896, 0.89575158],
        [0.11958906, 0.93022446, 0.22077052, 0.55416022]]),
 array([[0.24571991, 0.88457631, 0.36621282, 0.92500163, 0.1577782 ,
         0.51163158, 0.03704757],
        [0.84479899, 0.94036018, 0.86232133, 0.08444363, 0.20060532,
         0.38944742, 0.69973967],
        [0.38366021, 0.70343073, 0.58017754, 0.37005034, 0.03537206,
         0.51550666, 0.5328991 ]])]