In [5]:
# Imports
import numpy as np

In [97]:
# Import the tools
from sys import path
path.append('/Users/reid/dev/PythonCode/tm/tools')
# path.append('D:/PythonCode/tm/tools')
from tools import gen_inputs_outputs, logsig, lin, deriv_logsig, deriv_lin

In [98]:
# Define the size of the network
# Order by layers (input, layer1, layer2, ...)
# !!! No output layer yet, wait to gen inputs
layer_sizes = [3, 7]

In [99]:
# Gen inputs, outputs and size of the last layer
inputs, outputs, S = gen_inputs_outputs(layer_sizes[0])

In [9]:
# Append the output layer size
layer_sizes = np.array(layer_sizes + [S], dtype=int)

In [10]:
# Network shape
layer_sizes

array([4, 7, 3])

In [ ]:
#####
layer_sizes = np.array([1,2,1])

In [11]:
# Inputs
inputs

array([[0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 1, 0, 0],
       [0, 1, 0, 1],
       [0, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 0, 0, 0],
       [1, 0, 0, 1],
       [1, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 0, 0],
       [1, 1, 0, 1],
       [1, 1, 1, 0],
       [1, 1, 1, 1]])

In [12]:
# Outputs
outputs

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0]])

In [88]:
# Intialize the weights and biases randomly
# Also create the list to store the outputs of each layer
# Store the outptut for each layer
# Finally create the list of the sensitivities
weights_list = []
biases_list = []
n_list = []
a_list = []
s_list = []

In [89]:
for i in range(1, len(layer_sizes)):
    weights_list.append(np.random.rand(layer_sizes[i], layer_sizes[i-1]))
    biases_list.append(np.random.rand(layer_sizes[i], 1))
    n_list.append(np.empty((layer_sizes[i], 1), dtype=float))
    a_list.append(np.empty((layer_sizes[i], 1), dtype=float))
    s_list.append(np.empty((layer_sizes[i], 1), dtype=float))

In [ ]:
#####
weights_list = [
    np.array([[-0.27],[-0.41]]),
    np.array([[0.09, -0.17]])
]
biases_list = [
    np.array([[-0.48], [-0.13]]),
    np.array([[0.48]])
]
n_list = [

]

In [90]:
# Define the transfer functions
transfer_functions = [logsig, lin]

In [91]:
# Define the vectors with the derivatives of the transfer functions
# These need to be converted to dialation matrices
# but this is done after the partial derivatives are calculated
# so that the numerical values can be multiplied by the identity matrix
# makes my life easier
deriv_transfer_functions = [deriv_logsig, deriv_lin]

In [92]:
# Define a function to calculate the output of the network
# while also saving the data
# Assuming that the input is already a Rx1 matrix
def run_network(X):
    # Get the input for the first layer so that
    # no need to use X and can calculate
    # recursively
    n_list[0] = np.matmul(weights_list[0], X) + biases_list[0]
    a_list[0] = transfer_functions[0](n_list[0])

    # Calculate the rest of the outptut
    for i in range(1, len(weights_list)):
        n_list[i] = np.matmul(weights_list[i], a_list[i-1]) + biases_list[i]
        a_list[i] = transfer_functions[i](n_list[i])

In [93]:
run_network(inputs[1].reshape(layer_sizes[0], 1))

In [94]:
print(n_list, a_list, sep='\n\n')

[array([[0.78357139],
       [1.43554445],
       [0.82667657],
       [1.00080376],
       [0.97775035],
       [1.8818701 ],
       [0.61861453]]), array([[2.13210018],
       [3.21527884],
       [4.07125107]])]

[array([[0.68644932],
       [0.80776374],
       [0.69565175],
       [0.73121658],
       [0.72666161],
       [0.86782578],
       [0.64990338]]), array([[2.13210018],
       [3.21527884],
       [4.07125107]])]
