In [1]:
# Imports
import numpy as np
from sys import path
path.append("../tools")
from tools import *
import tools
print(dir(tools))

['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_bin_str_from_num', '_deriv_hardlim', '_deriv_lin', '_deriv_logsig', '_gen_input_unit_dict', '_hardlim', '_hardlims', '_hardsym', '_lin', '_logsig', 'array', 'ceil', 'count_params', 'count_params_reduced', 'deriv_hardlim', 'deriv_lin', 'deriv_logsig', 'e2', 'empty', 'empty_like', 'exp', 'gen_inputs_outputs', 'gen_pair_inputs', 'hardlim', 'hardlims', 'hardsym', 'lin', 'logsig', 'split', 'vectorize']


In [2]:
# Initialize the network architecture and inputs and outputs
R = 6
inputs, outputs, S = gen_inputs_outputs(R)

In [3]:
inputs = hardsym(inputs)
outputs = hardsym(outputs)

In [4]:
print(inputs, outputs)

[[-1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1  1]
 [-1 -1 -1 -1  1 -1]
 [-1 -1 -1 -1  1  1]
 [-1 -1 -1  1 -1 -1]
 [-1 -1 -1  1 -1  1]
 [-1 -1 -1  1  1 -1]
 [-1 -1 -1  1  1  1]
 [-1 -1  1 -1 -1 -1]
 [-1 -1  1 -1 -1  1]
 [-1 -1  1 -1  1 -1]
 [-1 -1  1 -1  1  1]
 [-1 -1  1  1 -1 -1]
 [-1 -1  1  1 -1  1]
 [-1 -1  1  1  1 -1]
 [-1 -1  1  1  1  1]
 [-1  1 -1 -1 -1 -1]
 [-1  1 -1 -1 -1  1]
 [-1  1 -1 -1  1 -1]
 [-1  1 -1 -1  1  1]
 [-1  1 -1  1 -1 -1]
 [-1  1 -1  1 -1  1]
 [-1  1 -1  1  1 -1]
 [-1  1 -1  1  1  1]
 [-1  1  1 -1 -1 -1]
 [-1  1  1 -1 -1  1]
 [-1  1  1 -1  1 -1]
 [-1  1  1 -1  1  1]
 [-1  1  1  1 -1 -1]
 [-1  1  1  1 -1  1]
 [-1  1  1  1  1 -1]
 [-1  1  1  1  1  1]
 [ 1 -1 -1 -1 -1 -1]
 [ 1 -1 -1 -1 -1  1]
 [ 1 -1 -1 -1  1 -1]
 [ 1 -1 -1 -1  1  1]
 [ 1 -1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1  1]
 [ 1 -1 -1  1  1 -1]
 [ 1 -1 -1  1  1  1]
 [ 1 -1  1 -1 -1 -1]
 [ 1 -1  1 -1 -1  1]
 [ 1 -1  1 -1  1 -1]
 [ 1 -1  1 -1  1  1]
 [ 1 -1  1  1 -1 -1]
 [ 1 -1  1  1 -1  1]
 [ 1 -1  1  1  1 -1]
 [ 1 -1  1  1

In [101]:
# Initialize empty weights and bias (only one layer)

# W = np.random.rand(S, R)
# b = np.random.rand(S, 1)

W = np.zeros((S, R), dtype=float)
b = np.zeros((S, 1), dtype=float)

In [102]:
# Define function to calculate error
def e(input, output):
    return output.reshape(S, 1) - (np.matmul(W, input.reshape(R, 1)) + b)

In [103]:
for i in range(10):
    for i in range(len(inputs)):
        W = W + np.matmul(e(inputs[i], outputs[i]), inputs[i].reshape(1, R))
        b = b + e(inputs[i], outputs[i])

/var/folders/0k/bydhdy6d4rd5bgm5xr_s4tdr0000gn/T/ipykernel_8772/56314522.py:3: RuntimeWarning: overflow encountered in matmul
  return output.reshape(S, 1) - (np.matmul(W, input.reshape(R, 1)) + b)
/var/folders/0k/bydhdy6d4rd5bgm5xr_s4tdr0000gn/T/ipykernel_8772/56314522.py:3: RuntimeWarning: invalid value encountered in add
  return output.reshape(S, 1) - (np.matmul(W, input.reshape(R, 1)) + b)
/var/folders/0k/bydhdy6d4rd5bgm5xr_s4tdr0000gn/T/ipykernel_8772/56314522.py:3: RuntimeWarning: invalid value encountered in matmul
  return output.reshape(S, 1) - (np.matmul(W, input.reshape(R, 1)) + b)


In [104]:
W

array([[nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan]])

In [105]:
E = np.empty([len(inputs), S], dtype=float)
for i in range(len(inputs)):
    E[i] = (e(inputs[i], outputs[i]).reshape(S))
    print(e(inputs[i], outputs[i]))

[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]


In [106]:
print(e2(E))

nan
